### Características de la práctica

En esta práctica el alumno aprenderá a utilizar la composición de
objetos mediante la utilización de listas de objetos. Además,
aprenderá las diferencias entre variables de instancia y variables de
clase, así como la conveniencia de
definir métodos privados, y de que los métodos de clase sólo pueden
acceder a las variables de clase, ya que no pueden acceder a las
variables de instancia. También practicará las operaciones
básicas sobre listas (*añadir*, *buscar*, *eliminar*).

### La clase `Libro`

La clase `Libro` contiene información sobre
un determinado libro, tal como el nombre del autor, el título, y el
precio base. Además, también posee información sobre el porcentaje de
IVA que se aplica para calcular su precio final. Nótese que el
porcentaje de IVA a aplicar es el mismo y es compartido por todos los
libros, siendo su valor inicial el 10.0%. Todos los atributos serán privados.
	
~~~ {.py}
▶ def __init__(self,...)
~~~
> Construye un objeto `Libro`. Recibe como parámetros, en el siguiente
> orden, el nombre del autor, el título, y el precio base del libro.

~~~ {.py}
▶ def autor(self)
▶ def titulo(self)
▶ def precio_base(self)
~~~

> Devuelven los valores correspondientes almacenados en el objeto (usa decoradores).

~~~ {.py}
▶ def precio_final(self)
~~~

> Devuelve el precio final del libro, incluyendo el IVA, según la
> siguiente ecuación.
>> $\mathit{PF}=\mathit{PB}+\mathit{PB}\times\mathit{IVA}\div100$

~~~ {.py}
▶ def __str__(self)
~~~

> Devuelve la representación textual del objeto, según el formato del
> siguiente ejemplo:
>> ~~~
>> (Isaac Asimov; La Fundación; 7.30; 10.0%; 8.03)
>> ~~~

~~~ {.py}
▶ def __eq__(self,other)
~~~

> Compara el libro actual (self) con el libro recibido como parámetro (other). Dos libros serán iguales si los son el autor y el titulo, independientemente de mayúsculas y minúsculas (*HINT*: usa lower()).

In [6]:
# Define la clase Libro
class Libro:
    IVA = 10

    def __init__(self, autor, titulo, precio):
        self.__autor = autor
        self.__titulo = titulo
        self.__precio_base = precio

    @property   
    def autor(self):
        return self.__autor

    @property   
    def titulo(self):
        return self.__titulo

    @property   
    def precio_base(self):
        return self.__precio_base

    def precio_final(self):
        return self.__precio_base + self.__precio_base * Libro.IVA / 100

    def __str__(self):
        return f"({self.__autor}; {self.__titulo}; {self.__precio_base:.2f}; {Libro.IVA:.1f}%; {self.precio_final():.2f})"

    def __eq__(self, other):
        salida = False
        if isinstance(other, Libro):
            salida = self.__autor.lower() == other.autor.lower() and self.__titulo.lower() == other.titulo.lower()

        return salida

In [8]:
# Crea tres objetos de la clase libro: 
l1 = Libro('Isaac Asimov', 'La Fundación', 7.30)
l2 = Libro('isaac AsimOV', 'la fundación', 38)
l3 = Libro('isaac AsimOV', 'la fundación', 38)

# Muestra los objetos por pantalla
print(l1)
print(l2)
print(l3)

# Muestra el IVA
print(Libro.IVA)

# Compara los tres objetos entre ellos para ver si son iguales dos a dos
print(l1 == l2)
print(l1 == l3)
print(l2 == l3)
#(Isaac Asimov; La Fundación; 7.30; 10.0%; 8.03)

(Isaac Asimov; La Fundación; 7.30; 10.0%; 8.03)
(isaac AsimOV; la fundación; 38.00; 10.0%; 41.80)
(isaac AsimOV; la fundación; 38.00; 10.0%; 41.80)
10
True
True
True


### La clase `LibroOferta`

La clase `LibroOferta` deriva de la clase `Libro`, por lo que contiene información sobre un determinado libro, pero además, permite especificar un determinado porcentaje de descuento (atributo privado), que será aplicado al **precio base** al calcular el precio final del libro.
	
~~~ {.py}
▶ def __init__(self,...)
~~~

> Construye un objeto `LibroOferta`. Recibe como parámetros, en el
> siguiente orden, el nombre del autor, el título, el precio base y el
> porcentaje de descuento del libro.

~~~ {.py}
▶ def descuento(self)
~~~

> Devuelve el porcentaje de descuento del libro.

~~~ {.py}
▶ def precio_final(self)
~~~

> Devuelve el precio final del libro, aplicando el descuento al precio
> base, e incluyendo el IVA, según las siguientes ecuaciones.

>> $\mathit{PX}=\mathit{PB}-\mathit{PB}\times\mathit{Descuento}\div100$

>> $\mathit{PF}=\mathit{PX}+\mathit{PX}\times\mathit{IVA}\div100$

~~~ {.py}
▶ def __str__(self)
~~~

> Devuelve la representación textual del objeto, según el formato del
> siguiente ejemplo:

>> ~~~
>> (Isaac Asimov; La Fundación; 7.30; 20.0%; 5.84; 10.0%; 6.424)
>> ~~~



In [20]:
# Define la clase LibroOferta
class LibroOferta(Libro):
    def __init__(self, autor, titulo, precio_base, descuento):
        super().__init__(autor, titulo, precio_base)
        self.__descuento = descuento

    @property
    def descuento(self):
        return self.__descuento

    def precio_final(self):
        PX = self.precio_base - self.precio_base * self.__descuento / 100
        return PX + PX * super().IVA / 100

    def __str__(self):
        #return f"{super().__str__()}, {self.__descuento}"
        PX = self.precio_base - self.precio_base * self.__descuento / 100
        return f"({self.autor}; {self.titulo}; {self.precio_base:.2f}; {self.__descuento:.1f}%; {PX:.2f}; {Libro.IVA:.1f}%; {self.precio_final():.2f})"


In [21]:
l = LibroOferta('Isaac Asimov', 'La Fundación', 7.30, 20)
print(l)

(Isaac Asimov; La Fundación; 7.30; 20.0%; 5.84; 10.0%; 6.42)


### La clase `Libreria`

La clase `Libreria`almacena múltiples
instancias de la clase `Libro` en una lista de ámbito privado.

**Nota 1:** las comparaciones que se realicen tanto del nombre del autor
  como del título del libro se deberán realizar sin considerar el caso
  (*mayúsculas* o *minúsculas*) de las letras que lo componen.

**Nota 2:** se recomienda la definición de métodos privados que
  simplifiquen y permitan modularizar la solución de métodos
  complejos.
  

~~~ {.py}
▶ def __init__(self)
~~~

> Construye un objeto `Libreria` vacío (sin libros).

~~~ {.py}
▶ def add_libro(...)
~~~

> Crea un nuevo objeto `Libro` con el nombre del autor, el título, y
> el precio base recibidos como parámetros, e invoca al método privado
> `__anyadir_libro` para añadirlo a la librería.
>> Invoca a: `__anyadir_libro`.

~~~ {.py}
▶ def add_libro_oferta(...)
~~~

> Crea un nuevo objeto `LibroOferta` con el nombre del autor, el título,
> el precio base y el porcentaje de descuento recibidos como parámetros, e invoca al método privado
> `__anyadir_libro` para añadirlo a la librería.
>> Invoca a: `__anyadir_libro`.

~~~ {.py}
▶ def rem_libro(...)
~~~

> Si existe el libro correspondiente al autor y título recibidos como
> parámetros, entonces elimina el libro de la librería invocando al
> método privado `__eliminar_libro`. Si no existe mostrar un mensaje por 
> pantalla.
>> Invoca a: `__buscar_libro` y `__eliminar_libro`.

~~~ {.py}
▶ def get_precio_base(...)
~~~

> Devuelve el precio base del libro correspondiente al autor y título
> recibidos como parámetros. Si el libro no existe en la librería,
> entonces devuelve cero.
>> Invoca a: `__buscar_libro`.

~~~ {.py}
▶ def get_precio_final(...)
~~~

> Devuelve el precio final del libro correspondiente al autor y título
> especificados. Si el libro no existe en la librería, entonces
> devuelve cero.
>> Invoca a: `__buscar_libro`.

~~~ {.py}
▶ def __str__(self)
~~~

> Devuelve la representación textual del objeto, según el formato del
> siguiente ejemplo (sin considerar los saltos de línea):
>> ~~~
>> [(George Orwell; 1984; 6.20; 10.0%; 6.82),
>>  (Philip K. Dick; ¿Sueñan los androides con ovejas eléctricas?; 3.50; 10.0%; 3.85),
>>  (Isaac Asimov; Fundación e Imperio; 9.40; 10.0%; 10.34),
>>  (Ray Bradbury; Fahrenheit 451; 7.40; 10.0%; 8.14),
>>  (Aldous Huxley; Un Mundo Feliz; 6.50; 10.0%; 7.15),
>>  (Isaac Asimov; La Fundación; 7.30; 10.0%; 8.03), 
>>  (William Gibson; Neuromante; 8.30; 10.0%; 9.13),
>>  (Isaac Asimov; Segunda Fundación; 8.10; 10.0%; 8.91),
>>  (Isaac Newton; Arithmetica Universalis; 10.50; 10.0%; 11.55)]
>> ~~~

~~~ {.py}
▶ def __anyadir_libro(self, libro)
~~~

> Si ya existe un libro de ese mismo autor, con el mismo título,
> entonces se reemplaza el libro anterior por el nuevo. En otro caso,
> añade el nuevo libro a la librería.
>> Invoca a: `__buscar_libro`.

~~~ {.py}
▶ def __eliminar_libro(self, indice)
~~~

> Elimina el libro que se encuentra en la posición de la lista recibida como
> parámetro. 

~~~ {.py}
▶ def __buscar_libro(self, ...)
~~~

> Busca en la librería la posición donde se **encuentra** un libro del
> autor recibido como primer parámetro, con el título recibido como
> segundo parámetro. Si lo encuentra, entonces devuelve el índice de la
> lista donde se encuentra el libro buscado. En caso de no
> encontrarlo, devuelve -1.
  

In [35]:
# Define la clase Libreria
class Libreria:
    def __init__(self):
        self.__libros = []
    
    def add_libro(self,autor,titulo,precio_base):
        l = Libro(autor,titulo,precio_base)
        self.__anyadir_libro(l)
    
    def add_libro_oferta(self,autor,titulo,precio_base,descuento):
        l = LibroOferta(autor,titulo,precio_base,descuento)
        self.__anyadir_libro(l)
    
    def rem_libro(self,autor,titulo):
        posicion = self.__buscar_libro(autor,titulo)
        if posicion != -1:
            # He encontrado el libro
            self.__eliminar_libro(posicion)
        else:
            print("El libro con autor", autor, "y titulo", titulo, "no ha sido encontrado")
    
    def get_precio_base(self,autor,titulo):
        posicion = self.__buscar_libro(autor,titulo)
        precio_base = 0
        if posicion != -1:
            # hago algo
            l = self.__libros[posicion] # Esto es el libro que hay en la posicion "posicion"
            precio_base = l.precio_base
        
        return precio_base
    
    def get_precio_final(self,autor,titulo):
        posicion = self.__buscar_libro(autor,titulo)
        precio_final = 0
        if posicion != -1:
            # hago algo
            l = self.__libros[posicion] # Esto es el libro que hay en la posicion "posicion"
            precio_final = l.precio_final()
        
        return precio_final
    
    def __str__(self):
        cad = "["
        for l in self.__libros:
            cad += str(l) + ",\n"
        cad = cad[:-2] + "]"
        return cad
    
    def __anyadir_libro(self, l):
        posicion = self.__buscar_libro(l.autor,l.titulo)
        if posicion != -1:
            # Voy a reemplazar el libro
            self.__libros[posicion] = l
        else: 
            # Añado el libro al final de la lista
            self.__libros.append(l)
       
    
    def __buscar_libro(self, autor, titulo):
         
        # Opcion 1    
        #for i in range(len(self.__libros)):
        #    libro = self.__libros[i]
        #    if libro.autor.lower() == autor.lower() and libro.titulo.lower() == titulo.lower():
        #        return i  
        #return -1
    
        # Opcion 2
        #indice = -1
        #encontrado = False
        #i = 0
        #while i < len(self.__libros) and not encontrado:
        #    libro = self.__libros[i]
        #    if libro.autor.lower() == autor.lower() and libro.titulo.lower() == titulo.lower():
        #        indice = i
        #        encontrado = True
        #return indice
        
        # Opcion 3
        libroTemp = Libro(autor,titulo,0)
        try: 
            indice = self.__libros.index(libroTemp)
        except ValueError:
            indice = -1
        return indice
    
    def __eliminar_libro(self, indice):
        del self.__libros[indice]



### Uso de las clases anteriores

Escribe el código que permita realizar una prueba de las clases anteriores. Así, deberá añadir a la librería los siguientes libros:
> ~~~
> ("george orwell", "1984", 8.20)
> ("Philip K. Dick", "¿Sueñan los androides con ovejas eléctricas?", 3.50)
> ("Isaac Asimov", "Fundación e Imperio", 9.40)
> ("Ray Bradbury", "Fahrenheit 451", 7.40)
> ("Aldous Huxley", "Un Mundo Feliz", 6.50)
> ("Isaac Asimov", "La Fundación", 7.30)
> ("William Gibson", "Neuromante", 8.30)
> ("Isaac Asimov", "Segunda Fundación", 8.10)
> ("Isaac Newton", "arithmetica universalis", 7.50)
> ("George Orwell", "1984", 6.20)
> ("Isaac Newton", "Arithmetica Universalis", 10.50)
> ~~~

De tal forma que al mostrar la representación textual de la librería
mostrará (considerando los saltos de línea '\n'):
> ~~~
> [(George Orwell; 1984; 6.20; 10.0%; 6.82),
>  (Philip K. Dick; ¿Sueñan los androides con ovejas eléctricas?; 3.50; 10.0%; 3.85),
>  (Isaac Asimov; Fundación e Imperio; 9.40; 10.0%; 10.34),
>  (Ray Bradbury; Fahrenheit 451; 7.40; 10.0%; 8.14),
>  (Aldous Huxley; Un Mundo Feliz; 6.50; 10.0%; 7.15),
>  (Isaac Asimov; La Fundación; 7.30; 10.0%; 8.03), 
>  (William Gibson; Neuromante; 8.30; 10.0%; 9.13),
>  (Isaac Asimov; Segunda Fundación; 8.10; 10.0%; 8.91),
>  (Isaac Newton; Arithmetica Universalis; 10.50; 10.0%; 11.55)]
> ~~~

In [36]:
# Crea una librería y añade los libros anteriores
lib = Libreria()
lib.add_libro("george orwell", "1984", 8.20)
lib.add_libro("Philip K. Dick", "¿Sueñan los androides con ovejas eléctricas?", 3.50)
lib.add_libro("Isaac Asimov", "Fundación e Imperio", 9.40)
lib.add_libro("Ray Bradbury", "Fahrenheit 451", 7.40)
lib.add_libro("Aldous Huxley", "Un Mundo Feliz", 6.50)
lib.add_libro("Isaac Asimov", "La Fundación", 7.30)
lib.add_libro("William Gibson", "Neuromante", 8.30)
lib.add_libro("Isaac Asimov", "Segunda Fundación", 8.10)
lib.add_libro("Isaac Newton", "arithmetica universalis", 7.50)
lib.add_libro("George Orwell", "1984", 6.20)
lib.add_libro("Isaac Newton", "Arithmetica Universalis", 10.50)
#lib.__buscar_libro(...) MAL, porque es un método privado

print(lib)

[(George Orwell; 1984; 6.20; 10.0%; 6.82),
(Philip K. Dick; ¿Sueñan los androides con ovejas eléctricas?; 3.50; 10.0%; 3.85),
(Isaac Asimov; Fundación e Imperio; 9.40; 10.0%; 10.34),
(Ray Bradbury; Fahrenheit 451; 7.40; 10.0%; 8.14),
(Aldous Huxley; Un Mundo Feliz; 6.50; 10.0%; 7.15),
(Isaac Asimov; La Fundación; 7.30; 10.0%; 8.03),
(William Gibson; Neuromante; 8.30; 10.0%; 9.13),
(Isaac Asimov; Segunda Fundación; 8.10; 10.0%; 8.91),
(Isaac Newton; Arithmetica Universalis; 10.50; 10.0%; 11.55)]


A continuación se eliminarán los siguientes libros:
> ~~~
> ("George Orwell", "1984")
> ("Aldous Huxley", "Un Mundo Feliz")
> ("Isaac Newton", "Arithmetica Universalis")
> ("James Gosling", "The Java Language Specification")
> ~~~

De tal forma que al mostrar la representación textual de la librería
mostrará (sin considerar los saltos de línea):
> ~~~
> [(William Gibson; Neuromante; 8.3; 10.0%; 9.13),
>  (Philip K. Dick; ¿Sueñan los androides con ovejas eléctricas?; 3.5; 10.0%; 3.85),
>  (Isaac Asimov; Fundación e Imperio; 9.4; 10.0%; 10.34),
>  (Ray Bradbury; Fahrenheit 451; 7.4; 10.0%; 8.14),
>  (Isaac Asimov; Segunda Fundación; 8.1; 10.0%; 8.91),
>  (Isaac Asimov; La Fundación; 7.3; 10.0%; 8.03)]
> ~~~

In [37]:
# Añade el código para eliminar los libros anteriores de la librería
lib.rem_libro("George Orwell", "1984")
lib.rem_libro("Aldous Huxley", "Un Mundo Feliz")
lib.rem_libro("Isaac Newton", "Arithmetica Universalis")
lib.rem_libro("James Gosling", "The Java Language Specification")
print(lib)

El libro con autor James Gosling y titulo The Java Language Specification no ha sido encontrado
[(Philip K. Dick; ¿Sueñan los androides con ovejas eléctricas?; 3.50; 10.0%; 3.85),
(Isaac Asimov; Fundación e Imperio; 9.40; 10.0%; 10.34),
(Ray Bradbury; Fahrenheit 451; 7.40; 10.0%; 8.14),
(Isaac Asimov; La Fundación; 7.30; 10.0%; 8.03),
(William Gibson; Neuromante; 8.30; 10.0%; 9.13),
(Isaac Asimov; Segunda Fundación; 8.10; 10.0%; 8.91)]


Finalmente se mostrará el precio final de los siguientes libros:

> ~~~
> getPrecioFinal("George Orwell", "1984"): 0.0
> getPrecioFinal("Philip K. Dick", "¿Sueñan los androides con ovejas eléctricas?"): 3.85
> getPrecioFinal("isaac asimov", "fundación e imperio"): 10.34
> getPrecioFinal("Ray Bradbury", "Fahrenheit 451"): 8.14
> getPrecioFinal("Aldous Huxley", "Un Mundo Feliz"): 0.0
> getPrecioFinal("Isaac Asimov", "La Fundación"): 8.03
> getPrecioFinal("william gibson", "neuromante"): 9.13
> getPrecioFinal("Isaac Asimov", "Segunda Fundación"): 8.91
> getPrecioFinal("Isaac Newton", "Arithmetica Universalis"): 0.0
> ~~~

In [41]:
# Añade el código que muestre la salida anterior
print("getPrecioFinal('George Orwell', '1984'):", lib.get_precio_final("George Orwell", "1984"))
print(lib.get_precio_final("Philip K. Dick", "¿Sueñan los androides con ovejas eléctricas?"))

getPrecioFinal('George Orwell', '1984'): 0
3.85
